version: '2'

services:
  app:
    build: .
    command: npm run dev
    ports:
      - 8080:8080
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - .mitmproxy:/root/.mitmproxy
